### ISSUE TITLE
Normal mode level completion not saving on Android

### ISSUE THREAD

**Issue by im-blad** [geode-sdk/website#14]
It's either because im using GDDL Integration mod, or it just does this on its own

When I beat a level, instead of the level complete screen, it makes me quit level

**Comment by TheSillyDoggo** [comment]
Not a geode website issue imo

**Comment by TheSillyDoggo** [comment]
Uhh delete the auto checkpoints mod

**Comment by im-blad** [comment]
> Uhh delete the auto checkpoints mod

You want me to reinstall it or what

**Comment by TheSillyDoggo** [comment]
The mod is bugged

**Comment by im-blad** [comment]
> The mod is bugged

And that's why I'm reporting that bug
