### ISSUE TITLE
add button explaining linux instructions

### ISSUE THREAD

**Issue by matcool** [geode-sdk/website#18]

**Comment by TymTymXD** [comment]
???

**Comment by sirbradinator** [comment]
I could help but I'm not contributer, how can I be one?

**Comment by matcool** [comment]
you know anyone can make pull requests. theres no need to be a contributer

**Comment by sirbradinator** [comment]
Is there even a Linux installer?

**Comment by RoootTheFox** [comment]
no
basically what u do is download the geode windows zip, extract it and put the files in ur gd folder
then set the launch args to `WINEDLLOVERRIDES="Xinput9_1_0=n,b"`
