### ISSUE TITLE
geometry dash crashing on click

### ISSUE THREAD

**Issue by TymTymXD** [geode-sdk/website#23]
logs: `2024-03-09T16:22:36+0100
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.21
Loader Commit: 06afbb8
Bindings Commit: ff44163
Installed mods: 53
Problems: 0

== Exception Information ==
C++ Exception: class std::runtime_error("invalid value")
Faulty Mod: <Unknown>

== Stack Trace ==
 - C:\windows\system32\kernelbase.dll + 4a738
 - C:\windows\system32\VCRUNTIME140.dll + 7e96
 - Z:\home\tymon\.local\share\Steam\steamapps\common\Geometry Dash\Geode.dll + 17932b
 - Z:\home\tymon\.local\share\Steam\steamapps\common\Geometry Dash\geode\unzipped\uproxide.quotes\uproxide.quotes.dll + 5e34
 - Z:\home\tymon\.local\share\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + ae203
 - Z:\home\tymon\.local\share\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + ad27d
 - 03AC2BC6
 - 000402BE
 - Z:\home\tymon\.local\share\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + be2f0
 - CCCCCC00

== Register States ==
EAX: 00e8f5ac
EBX: 19930520
ECX: 00000000
EDX: 00e8f5c0
EBP: 00e8f604
ESP: 00e8f5a0
EDI: 00e8f5c8
ESI: 00e8f634
EIP: 7b04a738

== Installed Mods ==
x | [v1.0.0] adam_729.randdeathsounds
x | [v1.1.1] adyagd.godlikefaces
x | [v1.1.3] adyagd.ingamelistmod
x | [v1.0.1] alphalaneous.happy_textures
x | [v1.0.0] alphalaneous_raydeeux.changefont19
x | [v1.0.6] bitz.customprofiles
x | [v1.0.3] bitz.moregames
x | [v1.0.3] bulletbot.gamemode_changer
x | [v1.0.0] capeling.colored_level_info_bg
x | [v1.0.5] capeling.gamemode_picker
x | [v1.1.4] capeling.icon_profile_2.2
x | [v1.0.0] capeling.usable_explorers
x | [v1.0.1] cdc.level_thumbnails
x | [v1.0.1] colon.gold_user_coins
x | [v1.0.0] creo.color_unlock_hack
x | [v1.0.0] creo.music_unlock_hack
x | [v4.1.3] cvolton.betterinfo
x | [v1.0.1] cvolton.misc_bugfixes
x | [v1.3.1] dankmeme.globed2
x | [v1.5.0] egg.icon_hack
x | [v1.3.1] elsai.a_daily_shop
x | [v1.0.3] elsai.copyright_remover_for_main_levels
x | [v2.5.2] fleym.nongd
x | [v1.5.2] geode.custom-keybinds
x | [v1.5.1] geode.devtools
x | [v2.0.0-beta.21] geode.loader
x | [v1.7.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.4.1] hiimjustin000.integrated_demonlist
x | [v6.3.3] hjfod.betteredit
x | [v1.0.5] hjfod.gdshare
x | [v1.0.5] hjfod.gmd-api
x | [v1.0.0] izzy.i_hate_you_top_lists
x | [v1.0.0] jojo989.main_menu_bg_customizer
x | [v1.2.2] legowiifun.unlisted_objects_in_editor
x | [v1.0.2] mat.run-info
x | [v2.1.0] prevter.openhack
x | [v1.1.3] shineua.geometrize2gd
x | [v1.0.2] slammy333.save_button
x | [v1.0.5] sofabeddd.colored_icon_kit
x | [v2.0.0] spaghettdev.gd-roulette
x | [v2024.229.0] tastyforreal.google-translate
x | [v2.8.0] techstudent10.discord_rich_presence
x | [v1.0.1] techstudent10.hide_locks
x | [v1.0.1] thesillydoggo.animatedprofiles
x | [v1.1.0] thesillydoggo.better_startpos_menu
x | [v1.0.0-beta.5] thesillydoggo.comment_emojis
x | [v1.0.3] thesillydoggo.icon_kit_switcher
x | [v1.6.6] tpdea.betterpause-Better
x | [v1.0.1] uproxide.autosong
x | [v1.1.2] uproxide.geodedevelopers
x | [v1.1.0] uproxide.quotes
x | [v1.5.3] zilko.xdbot
`

**Comment by TymTymXD** [comment]
PLEASE HELP

**Comment by RoootTheFox** [comment]
wrong repo + try removing the quotes mod

**Comment by TymTymXD** [comment]
i tried but didint work
