### ISSUE TITLE
Extreme lag on midrange GPU

### ISSUE THREAD

**Issue by flzpfnove** [geode-sdk/website#40]
If you open a menu in a menu in a menu etc, it has to compute the blur so many times the game drops to very low framerates.

You can recreate this by just (from the main menu) clicking the gear icon, graphics, advanced and pressing the info button on one of the settings (game drops to 8FPS on an RTX 3060).

A possible fix would be to only blur for the last shown menu, this way you achieve almost undistinguishable results while improving the performance by a lot. I'd write the code myself but I don't know how to write Geode mods.

**Comment by Alphalaneous** [comment]
This is the Geode website’s repo, not the mod’s repo, please redirect yourself to the BlurBG mod’s repo.

**Comment by flzpfnove** [comment]
oops!
